dbt-labs/dbt-bigquery

- CHANGELOG.md
- setup.py
resolves https://github.com/dbt-labs/dbt-core/issues/4171
Port of this PR from Core: https://github.com/dbt-labs/dbt-core/pull/4192
> Change Bigquery google-api-core max version dependency

- CHANGELOG.md
- dbt/adapters/bigquery/connections.py
resolves #47 
Solution for the bug I found with row policy access
I found the problem and a solution for it.
Because of some security in row access policy, when the user that is include in row access policy run a query with the table, he receive None as how much bytes is proccessed
[https://cloud.google.com/bigquery/docs/best-practices-row-level-security](url)
So with that dbt the `bytes_processed`return None value and break the `abs(bytes_processed)`
- [ x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ x] I have run this code in development and it appears to resolve the stated issue
- [ x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-bigquery next" section.
> Fix problem with row access policy doesnt return bytes proccessed.

- CHANGELOG.md
- dbt/include/bigquery/macros/materializations/incremental.sql
- tests/integration/incremental_schema_tests/models/incremental_append_new_columns.sql
- tests/integration/incremental_schema_tests/models/incremental_append_new_columns_remove_one.sql
- tests/integration/incremental_schema_tests/models/incremental_append_new_columns_remove_one_target.sql
- tests/integration/incremental_schema_tests/models/schema.yml
- tests/integration/incremental_schema_tests/test_incremental_schema.py
- tests/integration/incremental_schema_tests/tests/select_from_incremental_append_new_columns_remove_one.sql
- tests/integration/incremental_schema_tests/tests/select_from_incremental_append_new_columns_remove_one_target.sql
resolves https://github.com/dbt-labs/dbt-core/issues/4144
Using https://github.com/dbt-labs/dbt-core/pull/4170 changes, the goal is to retrieve the intersection from existing table columns and the tmp table columns for the condition to avoid referencing columns that wouldn't be in one or the other table and lead to a failure of the incremental run.
Snowflake equivalent: https://github.com/dbt-labs/dbt-snowflake/pull/38
> Use common columns for incremental schema changes

- CHANGELOG.md
- setup.py
Not sure why `dependabot` isn't working for `setup.py` here either. In any case:
- Try bumping google cloud/bigquery/api dependencies to include latest major version
- Remove `six`, which we added way back when to fix a dependency mistake in `dbt-bigquery==1.23.0`; we now require `>=1.25.0` (https://github.com/dbt-labs/dbt-core/pull/2007, https://github.com/googleapis/google-cloud-python/issues/9965). We haven't supported python2 for some time, so I don't see any reason to keep `six` hanging around
> Bump google dependency upper bounds, remove `six`

- CHANGELOG.md
- dbt/adapters/bigquery/connections.py
- dbt/adapters/bigquery/gcloud.py
- dbt/adapters/bigquery/impl.py
- tests/integration/base.py
- tests/integration/query_comments_test/test_query_comments.py
Updates to allow adapter to use new struct logger in dbt-core [#4176](https://github.com/dbt-labs/dbt-core/pull/4176)
> converted to use new struct logging

- .github/workflows/integration.yml
When a scheduled run fails, this will post it to slack
> Slack message for failed nightly runs

- CHANGELOG.md
- dbt/adapters/bigquery/connections.py
resolves #23 
Add possibility to configure custom scopes for Google Cloud OAuth down to the minimal set if needed. By default it too broad.
> Making scopes a configurable profile config option for BigQuery

- CHANGELOG.md
- dbt/adapters/bigquery/impl.py
resolves #64
We won't apply the `require_partition_filter` and `partition_expiration_days` options to a temporary table, because the incremental materialization with the `insert_overwrite` strategy applies the options even to the temporary table to over-write partitions.
> Don't apply `require_partition_filter` to a temporary table

- CHANGELOG.md
- tests/unit/utils.py
resolves #
co-author: @kwigley 
updated test to check for child types, was causing python 3.7 and 3.8 failures
> updated conversion tests to include child types

- dbt/adapters/bigquery/connections.py
resolves #68 
Add logic in `BigQueryConnectionManager.execute` to enrich the response with more info for UPDATE and SELECT statements. 
UPDATE responses will match that of other DML operations, while SELECT will return the following:
- `bytes_processed` = total reported bytes processed from running the SELECT statement
- `rows_affected` = number of rows in the query result
> enrich adapter response for UPDATE and SELECT queries

- CHANGELOG.md
- dbt/adapters/bigquery/connections.py
- dbt/adapters/bigquery/impl.py
- dbt/include/bigquery/profile_template.yml
- tests/integration/docs_generate_tests/test_docs_generate.py
- tests/unit/test_bigquery_adapter.py
resolves #45 
Description
This PR provides a fine-grained control of the timeout and retry to bq query with four dbt-profile configs
```
job_creation_timeout_seconds     # specific for initiate BQ job, to control the timeout of step 1, query()
job_execution_timeout_seconds    # specific for awaiting job result, to control the timeout of step 2, result()
job_retry_deadline_seconds       # to control the overal query, retry_deadline of _query_and_results()
job_retries                      # to control the overall query, retries of _query_and_results()
```
These settings would allow us to control the timeouts of step 1 and step 2 of the BigQuery on their own ( See below), hence maximizing the chances to mitigate different kinds of intermittent errors.
For example, we could set the configs …
> add new bq job timeout and retry config

- .github/workflows/stale.yml
Adding the stale messaging workflow we have in dbt-core to adapters
> Adding Stale message workflow throughout

- CHANGELOG.md
- dbt/adapters/bigquery/impl.py
resolves #107
This PR adds an additional condition in `get_table_options` for `require_partition_filter`. Essentially, both the `require_partition_filter` and `partition_by` options must both not be none for `require_partition_filter` to work. This way, non-partitioned tables cannot have `require_partition_filter` applied to them.
This should allow users to just put `require_partition_filter` in the dbt_project.yml file instead of needing to make sure they only add it to configs for models that has `partition_by` in it.
> Make sure partition_by is in config if setting require_partition_filter

- CHANGELOG.md
- dbt/adapters/bigquery/impl.py
resolves #104
When we would like to deal with partital dbt models as parts of all models with a service account to access the partital ones, dbt gets failed due to the lack of permissions for other models. So, we ignore the `google.api_core.exceptions.Forbidden` exception so that we skip errors because of the lack of permissions.
By the way, how can we imlement unit tests for the update? I am not sure if we have multiple service accounts are available on the CI jobs.
I used the repository to test the implementation, as I reported the issue #104.
https://github.com/yu-iskw/dbt-issue-with-multiple-service-accounts-on-bigquery
- [passed] `dbt compile` for partital resources
- [passed] `dbt run` for partital resources
- [passed] `dbt compile` for every resources
- [failed] `dbt run` for every …
> [#104] Ignore the `Forbidden` exception in `list_relations_without_caching`

- .github/workflows/integration.yml
adding a new `BIGQUERY_TEST_NO_ACCESS_DATABASE` env variable to main as we use current main branch to test against pr's so tests involving the new env var are currently failing
Will reference in changelog for primary PR as this is just a required pr to be able to properly test [111](https://github.com/dbt-labs/dbt-bigquery/pull/111) and provide a simple integration test for community contribution.
> Adding New ENV  var to file

- CHANGELOG.md
- dbt/adapters/bigquery/impl.py
- dev_requirements.txt
- pytest.ini
- tests/conftest.py
- tests/functional/adapter/test_basic.py
- tox.ini
resolves #135
Initial implementation of tests ported from dbt-adapter-tests
> Implement initial adapter tests on bigquery

- CHANGELOG.md
- dbt/adapters/bigquery/connections.py
- dbt/adapters/bigquery/impl.py
Meta notes:
- resolves #158, which is a likely regression in v1.1.0rc1
- will require backporting to `1.1.latest`, and probably a `1.1.0rc2` release
- will require an update to docs: https://docs.getdbt.com/reference/warehouse-profiles/bigquery-profile#job_execution_timeout_seconds
This has the effect of passing in `timeout=None` to `query_job.result` by default (rather than 300 seconds). Per [BigQuery's docs](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.job.QueryJob.html#google.cloud.bigquery.job.QueryJob.result), this is an optional value, with default `None`:
> The number of seconds to wait for the underlying HTTP transport before using retry. If multiple requests are made under the hood, timeout applies to each individual request.
This restores parity …
> Set job_execution_timeout_seconds default to None

- tests/conftest.py
- tox.ini
resolves #151
Support `oauth` method (i.e. `gcloud` CLI) by default. Much easier to set up than a service account passed (as JSON) to the env var
- ~This PR includes tests, or tests are not required/relevant for this PR~
- ~I have updated the `CHANGELOG.md` and added information about my change to the "dbt-bigquery next" section.~
> Add oauth target as default for functional tests

- dbt/adapters/bigquery/connections.py
- tests/functional/adapter/test_basic.py
resolves #
make sure validate connection won't fail due to profile doesn't have comment
> fix validate connection failing

- .github/workflows/integration.yml
- .github/workflows/main.yml
- .github/workflows/version-bump.yml
- CHANGELOG.md
- dev_requirements.txt
- tests/unit/utils.py
We haven't been keeping up with CI for the `1.0.latest` branch. Some things have changed or needed updating that haven't gotten backporting so this PR takes care of that and fixes CI
Backports / Fixes (all of these exist on `1.1.latest` already so we are good there):
- Update CI to run the Bigquery `1.0.latest` branch against the Core `1.0.latest` branch. 
- Backport #196. 
- Backport #93 - This was done for Core's `1.0.latest` branch already so that's why it's failing here.
> Fixing broken `1.0.latest` CI

- .github/workflows/integration.yml
resolves #215
Adding these environment variables to the GitHub Actions configuration in the default branch (currently `main`), so they they can be used with subsequent pull requests.
If these aren't configured in the default branch, then they won't be available for PRs.
> Env vars for grantees for testing

- .github/workflows/integration.yml
resolves #215 (again)
Adding these environment variables to the GitHub Actions configuration in the default branch (currently `main`), so they they can be used with subsequent pull requests.
If these aren't configured in the default branch, then they won't be available for PRs.
> Updated user / group names

- dbt/adapters/bigquery/connections.py
- dbt/adapters/bigquery/impl.py
resolves CT-861 (just opened)
Try using the same authentication methods for Dataproc + GCS that we're using for BigQuery, so we don't need to rely on the `GOOGLE_APPLICATION_CREDENTIALS` env var being set.
I still haven't been able to get this running on my local machine, unfortunately. `job_client.submit_job_as_operation` returns:
```
501 Received http2 header with status: 404
```
> Use same auth for Dataproc + GCS

- CHANGELOG.md
- dbt/include/bigquery/macros/materializations/incremental.sql
resolves #232
Minimal changes to support compatibility with dbt Core incremental materialization refactor
> Changes for incremental strategy refactor compatibility

- dbt/include/bigquery/macros/adapters.sql
- dbt/include/bigquery/macros/materializations/incremental.sql
- tests/functional/adapter/test_python_model.py
Implements the incremental materialization for bigquery. Nearly directly copied from [Ian's work in spark](https://github.com/dbt-labs/dbt-spark/pull/377/files#diff-786bb6587e86e50a2d01888eb2d4a5257e9a0025f75379214fa93cd5a033c9fbR131)
> Add incremental materializations

- requirements.txt
`requirements.txt` file breaks cloud pipeline
Removed optional `requirements.txt` file
> requirements.txt incorrect

- CHANGELOG.md
- dbt/adapters/bigquery/connections.py
- tests/integration/bigquery_test/test_bigquery_adapter_functions.py
resolves #92 
Adding job_id / project_id from the job executed by BQ to add a clean link to explore the runtime in the BQ UI.
Practically, it adds a link in your `-d` runs such as:
```
13:28:11.169553 [debug] [Thread-1 (]: BigQuery adapter: Job details accessible at https://console.cloud.google.com/bigquery?project=<project>&j=<jobId>&page=queryresults
```
> Add job_id/project_id to adapter response to enable easy job linking

- .changes/unreleased/Under the Hood-20220806-142912.yaml
- dbt/adapters/bigquery/connections.py
- tests/integration/bigquery_test/test_bigquery_adapter_functions.py
resolves #92 
Adding job_id / project_id from the job executed by BQ to add a clean link to explore the runtime in the BQ UI.
Practically, it adds a link in your `-d` runs such as:
```
13:28:11.169553 [debug] [Thread-1 (]: BigQuery adapter: Job details accessible at https://console.cloud.google.com/bigquery?project=<project>&j=bq:<location>:<jobId>&page=queryresults
```
Fixed version following revert from https://github.com/dbt-labs/dbt-bigquery/pull/225
> Add job_id/project_id to adapter response to enable easy job linking (fixed)

- .github/workflows/backport.yml
- .github/workflows/version-bump.yml
resolves #264 
Updates version bump to also generate changelog, uses centralized reusable workflow that all adapters (and eventually core) can also use.
Adds backport action now that changie is implemented.
> Shared version-bump and adding backport actions

- dbt/adapters/bigquery/python_submissions.py
- setup.py
- tests/functional/adapter/test_python_model.py
> Make storage and dataproc required Lib and disable unstable test

- .changes/unreleased/Under the Hood-20220920-151057.yaml
- dbt/include/bigquery/macros/materializations/table.sql
resolves #316
Enable pandas and pandas-on-Spark DataFrames for dbt Python models. Convert either of those types to Spark DataFrame before writing.
> Convert df to Spark DataFrame if it is a pandas or pandas-on-Spark DataFrame before writing

- .changes/unreleased/Features-20220919-232721.yaml
- dbt/adapters/bigquery/column.py
- dev-requirements.txt
- tests/functional/adapter/utils/test_data_types.py
resolves https://github.com/dbt-labs/dbt-bigquery/issues/315
required for https://github.com/dbt-labs/dbt-core/issues/5739
dbt-bigquery patch as required for https://github.com/dbt-labs/dbt-core/issues/5739 via https://github.com/dbt-labs/dbt-core/pull/5875.
> add type boolean

- dbt/include/bigquery/macros/materializations/table.sql
resolves #326
Uses the implementation [here](https://github.com/databricks/dbt-databricks/pull/196) by @ueshin.
There is a discussion [here](https://github.com/dbt-labs/dbt-spark/pull/474#discussion_r982414507) about how we could choose to optimize import load times in the future.
Choosing to ["make it right"](https://wiki.c2.com/?MakeItWorkMakeItRightMakeItFast) in this PR rather than ["make it fast"](https://wiki.c2.com/?MakeItWorkMakeItRightMakeItFast). (The performance cost for importing `pandas` was only ~1 second in local testing.)
- ⚠️ It would be great if we could add different test environments that do/don't have each of these libraries installed. In the meantime, we are just manually testing against environments that _do_ have them all available.
> try/except rather than find_spec for optional imports

- .changes/unreleased/Fixes-20221026-192327.yaml
- dbt/adapters/bigquery/connections.py
Resolves #362
fix args for console link logging, the params order were wrong on that invocation resulting in an incorrect link
Here the prototype of the function:
https://github.com/dbt-labs/dbt-bigquery/blob/4b22e68f8dd60ea6f21042f158b42adeb32d8a00/dbt/adapters/bigquery/connections.py#L521
> fix args for console link logging

- .pre-commit-config.yaml
resolves: [Flake8 took down the gitlab repository in favor of github](https://www.reddit.com/r/Python/comments/yvfww8/flake8_took_down_the_gitlab_repository_in_favor/)
Updating to [documented](https://flake8.pycqa.org/en/latest/user/using-hooks.html#usage-with-the-pre-commit-git-hooks-framework) github flake8 repo: https://github.com/pycqa/flake8.
> Bigquery Implementation of flake8 fix to swap gitlab for github

- tests/integration/docs_generate_tests/test_docs_generate.py
resolves #360 
makes a fix to `tearDown` method to target alternate schema name before calling default `tearDown` method for integration test
spike doc: https://www.notion.so/dbtlabs/Bigquery-Leftover-tests-artifacts-350aa89a047f44b3b3b1967aaff8367e
todo:
> [CT-1412] docs_generate integration test hanging artifacts

- tests/integration/defer_state_test/test_defer_state.py
resolves https://github.com/dbt-labs/dbt-bigquery/pull/374
Triggering manual backport due to weird issue around protected branches popping up not allowing us to update .latest branches
> [Backport][CT-1412] manual trigger of backport #391

- tests/integration/defer_state_test/test_defer_state.py
resolves #374 
Triggering manual backport due to weird issue around protected branches popping up not allowing us to update .latest branches
> [Backport][CT-1412] manual trigger of backport #390

- tests/integration/docs_generate_tests/test_docs_generate.py
resolves #373 
backports integration test fix
> [Backport] pr fix to docs_generate integration test hanging artifacts (#373)

- .changes/unreleased/Under the Hood-20221207-103505.yaml
- tests/integration/base.py
resolves #https://github.com/dbt-labs/dbt-core/issues/6139, https://github.com/dbt-labs/dbt-core/pull/6291
Minor changes to `run_dbt_and_capture` incorporating `StringIO` logic as a addition to the `capture_stdout_logs`  to be in parity with `dbt-core`
> [CT-1405] Bigquery minor changes for event logging

- .changes/unreleased/Under the Hood-20221207-151813.yaml
- tox.ini
resolves #
In tox 4, space-separated variables specified for passenv are not passed into the container.
```
[testenv:inline]
passenv = FOO BAR
```
:point_up: doesn't work on tox 4
```
[testenv:separate-lines]
passenv =
FOO
BAR
```
> updating passenv in tox

- .changes/unreleased/Under the Hood-20221207-151813.yaml
- .pre-commit-config.yaml
- tox.ini
resolves #
In tox 4, space-separated variables specified for passenv are not passed into the container.
```
[testenv:inline]
passenv = FOO BAR
☝️ doesn't work on tox 4
```
```
[testenv:separate-lines]
passenv =
FOO
BAR
```
> [BACKPORT] #411

- tox.ini
resolves #414 
fixes new spacing requirements for env variables in tox.ini post tox release of 4.0.0
> [BACKPORT] tox passenv spacing changes to 1.1.latest

- .github/workflows/release.yml
Release action needs to be manually trigger via workflow_dispatch and the commit needs to be the full SHA, not shorthand to be able to find workflow.
> swap trigger, update commit sha on release workflow

- .changes/unreleased/Fixes-20230109-105325.yaml
- .github/workflows/main.yml
- dbt/include/bigquery/macros/materializations/incremental_strategy/merge.sql
- setup.py
- tests/functional/test_incremental_materialization.py
resolves #457
Remove trailing whitespace elimination in bq_generate_incremental_merge_build_sql
> fix whitespace issue with incremental sql

- .changes/unreleased/Under the Hood-20230110-110016.yaml
- dbt/adapters/bigquery/connections.py
- dbt/adapters/bigquery/gcloud.py
- dbt/adapters/bigquery/impl.py
- dbt/adapters/bigquery/relation.py
- dev-requirements.txt
- tests/integration/schema_tests_test/test_schema_v2_tests.py
- tests/integration/simple_snapshot_test/test_simple_snapshot.py
- tests/integration/sources_test/test_sources.py
- tests/unit/test_bigquery_adapter.py
resolves #441 
Replace exception functions and rename exceptions. Currently point to a branch of core for testing.
> update exception names

- .changie.yaml
- .github/workflows/bot-changelog.yml
Backport #480 
Necessary to allow other back ports to work without conflicts. Since PR is no longer required on main, when a change is back ported it will not have the PR in the changelog yaml and will break changelog generation.
> [BACKPORT] Remove PR requirement from Changelog (#480)

- .changes/unreleased/Fixes-20230213-203317.yaml
- dbt/adapters/bigquery/python_submissions.py
resolves #531
GCP changed the default spark runtime version from 1.1 to 2.0 introducing some breaking changes.
> specify 1.1 in batch runtime config

- .changes/unreleased/Fixes-20230309-181313.yaml
- dbt/adapters/bigquery/impl.py
- dbt/include/bigquery/macros/materializations/incremental.sql
- tests/functional/adapter/test_python_model.py
- tox.ini
resolves #581 
The macro `bq_create_table_as` wasn't passing the compiled_code through into the underlying method
Note: Skipping the tests for now since the Dataproc serverless hasn't been stable. A follow-up PR should be moving the tests for python to execute on cluster only. All tests pass on the [Cluster mode run](https://github.com/dbt-labs/dbt-bigquery/actions/runs/4380640163/jobs/7667923167)
> [ADAP-353]: Fix for #581: Python incremental model

- .changes/unreleased/Fixes-20230315-130504.yaml
- tests/functional/adapter/test_persist_docs.py
resolves #605 
Apparently -- cannot yet find evidence of this -- bigquery no longer accepts that parent models contain populate fields; only their leaf nodes can. I've asked in the DBT Slack if anyone has information as a normal debugging routine has turned up nothing. I saw a suspect google decided in this newest version of the API to close a loophole or perhaps disbar a previously deprecated feature.
This one will require backports!
> Remove checks on non-leaf-field tags since they no longer can exist.

- .changes/unreleased/Fixes-20230315-130504.yaml
- tests/integration/persist_docs_tests/models-bigquery-nested/schema.yml
- tests/integration/persist_docs_tests/test_persist_docs.py
backport #607 
Manually done because of massive file differences between `main` and this PR which is pre test conversion roundup.
> Backport PR 607 manually to 1.1.latest.

- .changes/unreleased/Fixes-20230322-162200.yaml
- dbt/adapters/bigquery/impl.py
resolves #621
The dbt Core switch to Google protobuf changed the name of a function from `_make_ref_key_msg` to `_make_ref_key_dict`.
> Use _make_ref_key_dict instead of _make_ref_key_msg

- dev-requirements.txt
- tests/functional/adapter/test_constraints.py
resolves https://github.com/dbt-labs/dbt-core/issues/7154
Adds (and reorganizes) tests.
> add test for enforcing contracts on incremental materializations

- .changes/unreleased/Under the Hood-20230411-143129.yaml
- dbt/include/bigquery/macros/utils/get_columns_spec_ddl.sql
- dev-requirements.txt
resolves #656
Updates `bigquery__format_column` per change in https://github.com/dbt-labs/dbt-core/pull/7319/commits/100afd1856b1c69420825f9f9db186bfda041ec8.
This macro is brand-new in v1.5, so this isn't a breaking change for any existing users.
> Update `bigquery__format_column` per dbt-core#7319

- .changes/unreleased/Fixes-20230408-035117.yaml
- dbt/include/bigquery/macros/adapters.sql
resolves #609 
I'm confident I've got a working fix here; a little less confident on user experience. 
This is also my first time working with all of these systems involved with python models; interesting stuff. Lots of surface area to find a small fix.
When schema changes are performed inside a model and the target relation already exists (albeit in a now out-of-date form), the bigquery spark overwrite strategy fails ([I checked, there are no built-in alternatives](https://spark.apache.org/docs/1.4.0/api/java/org/apache/spark/sql/SaveMode.html)). 
Therefore, a step is needed to clear out any existing, corresponding target relation before attempting to build a model. I first attempted to do this inside of the Python model, but that only clears the model in the spark namespace. We must …
> add steps to drop existing tables on --full-refresh

- .changes/unreleased/Fixes-20230421-120450.yaml
- tests/functional/adapter/test_grant_access_to.py
* try waiting between consecutive calls to run_dbt to see if it is a concurrency issue
(cherry picked from commit 5b00086d59b20ce982f96121ea3803f68d81797b)
resolves #614
See #674
> ADAP-382: Address TestAccessGrantSucceeds sporadic failure (#674)

- .changes/unreleased/Fixes-20230202-010912.yaml
- dbt/adapters/bigquery/impl.py
- dbt/include/bigquery/macros/adapters.sql
- dbt/include/bigquery/macros/materializations/incremental.sql
- dbt/include/bigquery/macros/materializations/incremental_strategy/common.sql
- dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql
- dbt/include/bigquery/macros/materializations/incremental_strategy/merge.sql
- dbt/include/bigquery/macros/materializations/incremental_strategy/time_ingestion_tables.sql
- tests/functional/adapter/incremental/incremental_strategy_fixtures.py
- tests/functional/adapter/incremental/test_incremental_strategies.py
- tests/unit/test_bigquery_adapter.py
resolves #486
This PR refactors the usage of time ingestion partitioning to use the actual data_type to pick the right pseudo column (_PARTITIONTIME for timestamp/datetime & _PARTITIONDATE for date)
> Support all types of data_type using time ingestion partitioning

- .changes/unreleased/Fixes-20230427-141957.yaml
- dbt/include/bigquery/macros/materializations/incremental_strategy/time_ingestion_tables.sql
- tests/functional/adapter/incremental/incremental_strategy_fixtures.py
resolves #684
When including UDF with BigQuery, those needs to be wrapped in the `sql_header` as the syntax prevents them to be inlined anywhere in the code. Therefore, like [default implementation](https://github.com/dbt-labs/dbt-core/blob/d2f963e20ea945355db57ff3d34a318429a8bf1e/core/dbt/include/global_project/macros/materializations/models/table/create_table_as.sql#L21), we have to include them in the materialization specific macros.
> Fix UDF usage with time ingestion

- .changes/unreleased/Fixes-20230428-232904.yaml
- dbt/adapters/bigquery/impl.py
- tests/functional/test_delete_column_policy.py
resolves #687
This resolves the issue where policy tags attempting to be applied to structs (records) in BigQuery. These can only be applied to leaf nodes as described in the docs [here](https://cloud.google.com/bigquery/docs/column-level-security#struct_or_record)
> Fixes adding policy tags when a struct is defined in the yml

- tests/functional/adapter/test_persist_docs.py
Prompted by issue #687 and PR #688 
Stemming from a lack of documentation, I didn't realize the patch 400 error was happening because policy tags were being applied (but only an empty list of them!) to non leaf fields, namely the inner struct (which itself has an inner struct with leaf fields). My PR #607  was misguided as a result.
My current working understanding is that a leaf field is something tied to a STRUCT(). These can have inner (cf. nested) STRUCTS, but these are not leaf fields. Only true columns are leaf fields. Thus, if the data type happens to be a record (the internal type of a STRUCT), his policy tag mechanism errors out with the 400 response.
In pr #542 , this bug was introduced indirectly [at this line](https://github.com/dbt-labs/dbt-bigquery/pull/542/files#diff-96ff53d …
> Revert PR 607

- .changes/unreleased/Fixes-20230509-222705.yaml
- dbt/adapters/bigquery/connections.py
> Add limit to execute signature for consistency with dbt-core

- .github/workflows/backport.yml
- .github/workflows/bot-changelog.yml
- .github/workflows/integration.yml
- .github/workflows/main.yml
- .github/workflows/release-branch-tests.yml
Please merge this update today! [node 12 support dropping tomorrow](https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/) and these version updates to Github Actions get ahead of that. Resolves RELENG-144
> update used gh actions ahead of node12 deprecation

- tests/functional/adapter/upload_file_tests/test_upload_file.py
resolves #
changing `upload_result.success` to `upload_result.results[0].status` in upload_file functional tests due to the error `AttributeError: 'RunResultsArtifact' object has no attribute 'success'` because `RunResultArtifacts` doesn't have access to `status` param of `RunResultsOption`/`RunResult` without digging deeper into stack.
This should fix recent ci/cd failures.
> [Fix] small change to test pathing for assert clause

- .changes/unreleased/Breaking Changes-20230530-174051.yaml
- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
- .github/workflows/nightly-release.yml
- CONTRIBUTING.md
- dev-requirements.txt
- setup.py
- tox.ini
resolves dbt-labs/dbt-core#7082
Drop support for python 3.7
> Drop support for py37

- .changes/unreleased/Features-20230604-034603.yaml
- dbt/adapters/bigquery/connections.py
- dbt/adapters/bigquery/impl.py
PR to bring adapter in parity with [this core PR](https://github.com/dbt-labs/dbt-core/pull/7741).
Now will use the bigquery adapter query and will show all credential lines in `_connection_keys`.
In the connection keys, flag any that are sensitive and should not be shown to users in plaintext
> Standardize the adapter for core debug changes.

- .changes/unreleased/Dependencies-20230618-220517.yaml
- setup.py
Resolves #777
Found while testing https://github.com/dbt-labs/dbt-core/pull/7368 via https://github.com/dbt-labs/dbt-bigquery/pull/774
Conversation in https://github.com/dbt-labs/dbt-bigquery/pull/774#discussion_r1231184097
- ~This PR includes tests, or tests are not required/relevant for this PR~
- ~I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR~
> Rm agate as explicit dep

- .changes/unreleased/Fixes-20230609-132727.yaml
- dbt/adapters/bigquery/python_submissions.py
- tests/functional/adapter/test_python_model.py
- tox.ini
resolves #577 
GCP async interface offers two configurations that both accept the same type: `retry` and `polling`. The difference is that `retry` configures each individual polling request while `polling` configures the long running operation (i.e. how long to poll for and how frequently to poll). We have been setting `retry` and not `polling` resulting in unexpected behavior in job configuration.
> Pass python model timeout to polling instead of retry

- .changes/unreleased/Fixes-20230626-105156.yaml
- dbt/adapters/bigquery/dataset.py
- dbt/adapters/bigquery/impl.py
- tests/unit/test_dataset.py
resolves #770 
remove call to dataset update if dataset has not changed
> Avoid unnecessary grant call

- .changes/unreleased/Breaking Changes-20230530-174051.yaml
- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
- CONTRIBUTING.md
- dev-requirements.txt
- setup.py
- tox.ini
Dropping support for py37 backport (#742)
> [Backport 1.4.latest] Dropping support for py37 (#742)

- .changes/unreleased/Breaking Changes-20230530-174051.yaml
- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
- CONTRIBUTING.md
- setup.py
- tox.ini
Dropping support for py37 backport (#742)
> [Backport 1.3.latest] Dropping support for py37 (#742)

- .changes/unreleased/Breaking Changes-20230530-174051.yaml
- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
- CONTRIBUTING.md
- setup.py
- tox.ini
Backport bc8b4a4a3eff0b4a0f0e1a760c35f6e26e4bde21 from #795.
> [Backport 1.1.latest] Dropping support for py37 (#742)

- .changes/unreleased/Fixes-20230628-162853.yaml
- tests/unit/utils.py
resolves #https://github.com/dbt-labs/dbt-core/pull/7955
> Remove dependent_projects argument from PartialProject call in unit tests

- .changes/unreleased/Fixes-20230630-213112.yaml
- .github/pull_request_template.md
- dbt/adapters/bigquery/column.py
- dbt/adapters/bigquery/impl.py
- dbt/include/bigquery/macros/utils/get_columns_spec_ddl.sql
- tests/unit/test_column.py
resolves https://github.com/dbt-labs/dbt-bigquery/issues/782
resolves https://github.com/dbt-labs/dbt-bigquery/issues/781
Handles scenarios where a nested column type may be specified both at the struct-level (e.g. `b.id: int`, `b.name: string`) and parent level `b: struct`. Additionally handles when parent level data_type is used to specify an array of structs. 
This PR resolves two issues -- initially I had aimed to just tackle 782 on its own by ignoring a top-level data_type if specified (preserving its constraints) but the top-level array specification was just a couple additional lines at that point, and figured reviewing / testing it all together would be more straightforward since the issues and affected codepaths were very closely related. 
- scope of changes is entirely covered …
> Contracts: Handle struct column specified both at root and nested levels + arrays of structs

- .changes/unreleased/Features-20230712-014350.yaml
- dbt/adapters/bigquery/connections.py
- dbt/adapters/bigquery/impl.py
- tests/functional/adapter/utils/test_utils.py
resolves #805
In CLI contexts MetricFlow will issue dry run queries as part
of its warehouse validation operations, and so we are adding a
validate_sql method to all adapters.
The implementation we use for SQLAdapter classes does not
work with BigQuery, as BigQuery does not support the EXPLAIN
keyword.
This PR adds support for the validate_sql method to BigQuery. It
does so by creating a BigQuery-specific `dry_run` method on the
BigQueryConnectionManager. This simply passes through the input SQL
with the `dry_run` QueryJobParameter flag set True. This will result
in BigQuery computing and returning a cost estimate for the query,
or raising an exception in the event the query is not valid.
Note: constructing the response object involves some repetitive value
extraction from the QueryResult …
> Add support for validate_sql method to BigQuery

- .changes/unreleased/Features-20230517-092205.yaml
- dbt/adapters/bigquery/connections.py
- dbt/adapters/bigquery/python_submissions.py
- test.env.example
- tests/conftest.py
This reverts commit a42e13d8023123102c4d1aeefdfa6cd6246c4768.
resolves #822
We discovered that #727's implementation doesn't work when multiple Python models are used. So we are reverting PR to remove it as a feature shipped as part of `1.6.0`. Instead, we intend to ship an alternate implementation in the next minor version in `1.7.0`
> Revert "Add `batch_id` param to profile  to pass along with `dataproc_v1.CreateBatchRequest` (#727)"

- .changes/unreleased/Fixes-20230325-204352.yaml
- dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql
- tests/functional/adapter/incremental/incremental_strategy_fixtures.py
- tests/functional/adapter/incremental/test_incremental_strategies.py
Resolves #427
Resolves #556
As described in #427, static insert overwrite, when involving `on_schema_change != 'ignore'` would create a temp table to check for a schema change anyway.
It fixes as well:
- In case, `on_schema_change = 'ignore'` with dynamic insert overwrite where the SQL header would not be added
- In case, we would have static insert overwrite with `on_schema_change != 'ignore'` where the temp table would not be deleted
> Use tmp table in static insert overwrite

- .github/workflows/integration.yml
- dev-requirements.txt
- tox.ini
resolves #8081 
~~[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/#~~ n/a
Datadog not ingesting test data for flaky test visibility
Adds env vars to turn on test visibility in datadog.  [Datadog docs](https://docs.datadoghq.com/continuous_integration/tests/python/?tab=cloudciprovideragentless#compatibility)
Updates the tox command to include the `--ddtrace` flag only when running in CI.
> add datadog env vars

- .changes/unreleased/Under the Hood-20230724-164946.yaml
- .github/workflows/stale.yml
The stale workflow uses an old version
Update the stale workflow to use the centralized version.
> Update stale workflow to use centralized version

- .github/workflows/release.yml
Moves alerts to the new adapter channel. The secret is already there so we don't need to wait to merge.
> Move Alerts

- tox.ini
Backport eb1b97edaf82168ca9837447e4b5d75d874099b7 from #875.
> [Backport 1.3.latest] add env vars for datadog test visibility

- .changes/unreleased/Fixes-20230821-180758.yaml
- tests/functional/adapter/expected_stats.py
resolves #889 
currently believe that adding this integer check https://github.com/dbt-labs/dbt-core/pull/8306 for agate changes availability of use of `AnyFloat`
swap to AnyInteger
Todo:
- backport to 1.6.latest if approved and merged.
> change type of expected value

- .changes/unreleased/Fixes-20230818-214616.yaml
- dbt/adapters/bigquery/__init__.py
- dbt/adapters/bigquery/impl.py
- tests/unit/test_bigquery_adapter.py
resolves #886
The API returns sometimes upper cased fields such `timePartitioning.type` and in case the user config has also a different casing, we should do a case insensitive check on partition matching.
It introduce a proper case insensitive check on partition field matching
> case insensitive check on partition matching

- .changes/unreleased/Under the Hood-20230829-122918.yaml
- dbt/include/bigquery/macros/adapters.sql
- dbt/include/bigquery/macros/relations/cluster.sql
- dbt/include/bigquery/macros/relations/drop.sql
- dbt/include/bigquery/macros/relations/options.sql
- dbt/include/bigquery/macros/relations/partition.sql
- dbt/include/bigquery/macros/relations/rename.sql
- dbt/include/bigquery/macros/relations/table/options.sql
- dbt/include/bigquery/macros/relations/view/options.sql
Materialized views work will require macros that are relation-agnostic dispatching to relation-specific macros. This will make `adapters.sql` more difficult to understand, and the resulting PR more difficult to process.
Break the MV work into refactoring and feature work. This PR represents the refactoring half, where macros are moved but not altered. The code and signature remain the same. This is effectively the same code, but moved to different files (which does not affect how the macros are read).
> ADAP-842: Reformat macro file structure to be more modular and organizaed

- .changes/unreleased/Fixes-20230907-161347.yaml
- tests/functional/adapter/expected_stats.py
resolves #915 
change to agate_helper in core requires update to data type expected value in test.
This pr may seem familiar is a new version of one we recently reverted in order to make release see #890  and #894 
merge into main and backport to 1.6.latest when core does
> update expected values

- .changes/unreleased/Fixes-20230911-005506.yaml
- dbt/adapters/bigquery/column.py
- tests/functional/adapter/incremental/test_incremental_on_schema_change.py
to fix time ingestion partitioning table creation
resolves #913
When time ingestion table are created, every field is used with their data types to generate the DDL statement.
When using fields in a STRUCT that contains a field that is a reserved word, it would fail if it's not quoted which is the current issue.
Adding the quote in the data types of struct elements should fix the problem.
> quote column names in data types

- .changes/unreleased/Under the Hood-20230921-155645.yaml
- dbt/adapters/bigquery/connections.py
- dbt/adapters/bigquery/impl.py
- tests/functional/adapter/test_grant_access_to.py
- tests/unit/test_bigquery_adapter.py
- tests/unit/test_bigquery_connection_manager.py
- pull in changes from #935 
- update impl ConnectionManager typing and move list_datasets into BigQueryConnectionManager
- refactor unit tests and add one to cover list_datasets
resolves #
> Address type annotation issues and clean up impl

- .changes/unreleased/Under the Hood-20230925-143628.yaml
- dev-requirements.txt
- tests/functional/adapter/dbt_show/test_dbt_show.py
resolves https://github.com/dbt-labs/dbt-bigquery/issues/940
[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/# N/A
Adding tests for dbt show introduced in https://github.com/dbt-labs/dbt-core/pull/8641
> Add dbt show tests

- .changes/unreleased/Fixes-20231005-235950.yaml
- dbt/adapters/bigquery/connections.py
- tests/functional/adapter/query_comment_test/test_job_label.py
resolves #863
A regression appears in the last release of `dbt-bigquery`. A user can previously add labels to a BigQuery job thanks to a macro returning a mapping. In the version 1.6.0, this was no longer possible even if the project is set to activate this feature. 
The proposed solution is to use, instead of `self.profile.query_comment` (which is the not-rendered Jinja macro), `self.query_header.comment.query_comment` (the JSON rendered query comments).
I added some safeguards to make sure that `self.query_header.comment.query_comment` is not null but during the runtime, it should never be the case because of the following succession of functions and methods calls during a run command:
1. The query labels are sent with a `run` command, [command decorated with the decorator …
> [fix] Use rendered query comment for job labels

- dbt/adapters/bigquery/connections.py
resolves #
we implemented a change in #955 to fix query_header in doing so moved `self.query_header` into the same conditional logic as `self.profile` and used a _walrus_ operator to assign and check which while clean does make parse code quickly slightly harder.
to functionalize the small snippet and create a small change by making it to two nested if statements and moving the empty set of variable to top of function.
> a slight rework of 955 to keep a seperation of concerns

- .github/workflows/nightly-release.yml
- tests/functional/adapter/test_grant_access_to.py
Currently nightly release tests fail since core does not view the supplied adapter version as valid semver: 
`dbt.exceptions.SemverError: "1.5.6.dev10092023" is not a valid semantic version.` 
This change would have "dev" be a build tag instead of a patch version, so the new version be: 1.5.6+dev10092023
resolves #
> test against 1.7.latest release branch and fix semver

- .changes/unreleased/Under the Hood-20231005-115800.yaml
- dbt/adapters/bigquery/column.py
- dev-requirements.txt
- tests/functional/adapter/constraints/test_constraints.py
resolves #953
Need to match changes in https://github.com/dbt-labs/dbt-core/pull/8592
Fix the test.   Add TEXT => STRING conversion to TYPE_LABELS.
> Use branch 8007-contract_type_aliasing

- .changes/unreleased/Features-20230426-152526.yaml
- dbt/include/bigquery/macros/materializations/table.sql
- tests/functional/adapter/test_python_model.py
resolves #680
Currently, Python models do not support table creation with partition_by and cluster_by when supplied to the model configuration, despite the spark-bigquery-connector having support for it with [indirect save mode](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#writing-data-to-bigquery).
For more details, see #680
> [ADAP-492] Support partition_by and cluster_by on python models (#680)

- tests/functional/adapter/utils/fixture_get_intervals_between.py
- tests/functional/adapter/utils/test_utils.py
resolves https://github.com/dbt-labs/dbt-core/issues/8172
In https://github.com/dbt-labs/dbt-core/issues/8172 we moved the `date_spine` macro and sub macros from dbt-utils to dbt-core. As such we should begin testing these macros to ensure they work properly on this adapter.
Begin running the tests for the `date_spine` macro and sub macros
> Add tests for `date_spine` macro, and sub macros

- .changes/unreleased/Fixes-20231021-154237.yaml
- .changes/unreleased/Fixes-20231023-082312.yaml
- dbt/adapters/bigquery/connections.py
- tests/functional/adapter/dbt_show/test_dbt_show.py
resolves #972
`dbt show --select` currently breaks when attempted on a `json` field because of [this bigquery python client issue](https://github.com/googleapis/python-bigquery/issues/1500)
Patch as suggested by @dbeatty10 
```
def _json_from_json(value, _):
"""NOOP string -> string coercion"""
return json.loads(value)
bigquery._helpers._CELLDATA_FROM_JSON["JSON"] = _json_from_json
```
> Patch for `dbt show` for a model with a `struct` column containing a `json` datatype

- .changes/unreleased/Fixes-20231025-131907.yaml
- setup.py
resolves #979
> we [import `POLLING_PREDICATE` from `google.api_core.future.polling` ](https://github.com/dbt-labs/dbt-bigquery/blob/6a3f45897f4e7ccd41de584d64605e7342dc75e0/dbt/adapters/bigquery/python_submissions.py#L4) but `google.api_core.future.polling.POLLING_PREDICATE` is available on `google-api-core` version `2.11.0`+. 
> ensure that this version is enforced and create a pin
> Lower bound of `2.11.0` for `google-api-core`

- .changes/unreleased/Fixes-20231030-222134.yaml
- dbt/include/bigquery/macros/catalog.sql
- tests/functional/adapter/catalog_tests/files.py
- tests/functional/adapter/catalog_tests/test_relation_types.py
resolves #995, dbt-labs/dbt-core#8864
Materialized views were being mapped as tables in catalog queries.
- write a test demonstrating the issue
- update the catalog query to return the correct type
> ADAP-972: Fix issue where materialized views were being mapped as tables in catalog queries

- .changes/unreleased/Fixes-20231107-100905.yaml
- dbt/adapters/bigquery/impl.py
- dev-requirements.txt
- tests/functional/adapter/test_simple_seed.py
- tests/unit/mock_adapter.py
resolves #1003
dbt Core introduced an agate Integer type. This provides code to support it and a test for a bug constructing an empty seed.
Add a "convert_integer_type" method to dbt/adapters/bigquery/impl.py
> Support agate Integer type, test with empty seed

- .changes/unreleased/Fixes-20231107-174352.yaml
- dbt/adapters/bigquery/relation.py
- dbt/adapters/bigquery/relation_configs/_partition.py
- tests/functional/adapter/materialized_view_tests/_files.py
- tests/functional/adapter/materialized_view_tests/test_materialized_view.py
resolves #1007
Users cannot recreate a materialized view if it does not have any changes. The configuration change collection is not being recognized as an empty set of changes.
The check currently looks for the existence of the config change collection instead of whether it has any changes. Update the check to look for the existence of changes instead of the object itself.
> ADAP-1017: Fix configuration change monitoring for scenarios with no changes

- .changes/unreleased/Fixes-20231105-125740.yaml
- dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql
- tests/functional/adapter/incremental/incremental_strategy_fixtures.py
- tests/functional/adapter/incremental/test_incremental_strategies.py
resolves #896
If an incremental model (with static partition replacement) has an inline SQL comment, this results in an invalid SQL statement.
Change so that there is a line break after the SQL.
~Test has not been added as it is expected to be added by https://github.com/dbt-labs/dbt-core/issues/8487~
> Fix inline comments (--) on the last line of an incremental model (partition replacement)

- .changes/unreleased/Under the Hood-20231117-121214.yaml
- dev-requirements.txt
- tests/functional/adapter/empty/test_empty.py
resolves #1029
[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/# N/A
https://github.com/dbt-labs/dbt-core/pull/8971 introduced a new `--empty` flag that required implementation changes to the BaseRelation.
Add tests in dbt-bigquery to ensure expected behaviour of the new `--empty` flag when running with dbt-bigquery.
> add tests for --empty flag

- .changes/unreleased/Features-20231218-155409.yaml
- dbt/adapters/bigquery/impl.py
- tests/boundary/test_bigquery_sdk.py
- tests/functional/adapter/sources_freshness_tests/files.py
- tests/functional/adapter/sources_freshness_tests/test_get_relation_last_modified.py
resolves #938
The current implementation of source freshness requires querying the data and requires the user provide a datetime field. This is slower and more expensive than it should be. It doesn't scale across multiple models. And some models do not have an appropriate datetime field.
Use source metadata where available.
NOTE: We are releasing to `1.7.latest` first, which is unusual. This PR is a set of cherry picks from #1060. The latter will be updated and merged post adapter/core split work.
>  Implementation of metadata-based freshness

- dbt/adapters/bigquery/impl.py
- dev-requirements.txt
- tox.ini
> add TableLastModifiedMetadata capability enum to impl and specify timeout

- .changes/unreleased/Under the Hood-20231116-062142.yaml
- dbt/adapters/bigquery/impl.py
resolves #1018
https://github.com/dbt-labs/docs.getdbt.com/pull/4419
The source code says [here](https://github.com/dbt-labs/dbt-bigquery/blob/64e042a2349f17342f7af96d559e4e3a5138a49e/dbt/adapters/bigquery/impl.py#L115-L116) that `primary_key` and `foreign_key` are enforced.
But as noted in https://github.com/dbt-labs/docs.getdbt.com/pull/4419, they are supported, but **_not_** enforced.
Update the `CONSTRAINT_SUPPORT` to reflect what the BigQuery docs say [here](https://cloud.google.com/blog/products/data-analytics/join-optimizations-with-bigquery-primary-and-foreign-keys) and [here](https://cloud.google.com/bigquery/docs/information-schema-table-constraints).
> Primary and foreign key constraints are not enforced in BigQuery

- .changes/unreleased/Fixes-20231107-174352.yaml
- dbt/adapters/bigquery/relation.py
- dbt/adapters/bigquery/relation_configs/_partition.py
- tests/functional/adapter/materialized_view_tests/_files.py
- tests/functional/adapter/materialized_view_tests/test_materialized_view.py
Backport 64e042a2349f17342f7af96d559e4e3a5138a49e from #1009.
> [Backport 1.7.latest] Fix configuration change monitoring for scenarios with no changes (#1009)

- .changes/unreleased/Fixes-20240201-145323.yaml
- dbt/include/bigquery/macros/catalog/catalog.sql
resolves #1079
External tables don't show up in `COLUMN_FIELD_PATHS` metadata. When generating the catalog, these columns were returning null values for external tables. `dbt docs generate` does not account for null values for these fields, in particular for the column index.
Coalesce the queried values with default values:
- column_name: `'<unknown>'`
- column_index: `1`
- column_type: `'<unknown>'`
- column_comment: `''`
The `'<unknown>'` values align with the previous implementation, as does the `1`. In the previous implementation, this was implicit, as it was calculated as a `row_number` across null fields. In this implementation, it's explicitly `1`, as there is really only one field, "the data". The column comment in the original implementation was null in this scenario; this is an …
> Fix null column index issue during `dbt docs generate` for external tables

- dev-requirements.txt
- tests/functional/adapter/test_grant_access_to.py
- add dbt-core back to dev-requirements.txt
resolves #1080 
> Add dbt-core install back to dev-requirements.txt

- .changes/unreleased/Fixes-20240219-103324.yaml
- dbt/adapters/bigquery/connections.py
- tests/functional/test_job_timeout.py
- tests/unit/test_bigquery_adapter.py
* remove custom query job async timeout logic
---------
Co-authored-by: Mike Alfare <13974384+mikealfare@users.noreply.github.com>
(cherry picked from commit 5501cd34b12965e0380952bdbb65fd52f49b49f5)
resolves #
> Remove custom query job async timeout logic (#1109)

- setup.py
- tests/functional/adapter/test_grant_access_to.py
- use dynamic schema in test_grant_access_to.py
- use dynamic schema in test_grant_access_to.py
- revert setup
- update dbt-common dependency to <2.0
resolves #
> update dbt-common dependency to <2.0

- .github/workflows/main.yml
- tests/functional/adapter/test_grant_access_to.py
As we no longer require dbt-core on install we can't rely on `dbt --version` being present instead we can simply check that the expected adapter is import-able
resolves #
> Fix wheel/sdist check

- .changes/unreleased/Features-20240318-032256.yaml
- .github/workflows/release-internal.yml
resolves 38 of epic
This PR adds a workflow file for bigquery testing. It is based on [the already working redshift one](https://github.com/dbt-labs/dbt-redshift/pull/732). I assume there will be some quirks to work out. Also, we'll need to add aws secrets.
> Add Bigquery internal build process workflow 

- .changes/unreleased/Fixes-20240322-113720.yaml
- dbt/adapters/bigquery/connections.py
resolves #1146 
the field `keyfile` could have an argument to be a quasi secret level like field that possibly should be removed from debug and being called in jinja
> remove `keyfile` from `_connection_keys`

- .changes/unreleased/Fixes-20240327-210249.yaml
- setup.py
resolves #1152
`google-cloud-bigquery==3.20` added `pyarrow>=3.0` as a dependency for the `pandas` extra and we are not declaring the `pandas` extra. Either we are using functionality that requires the `pandas` extra and were not aware or this is a required dependency and not an extra dependency.
Install `google-cloud-bigquery[pandas]>=3.0,<4.0`
> Add `pandas` extra for `google-cloud-bigquery` to pick up missing `pyarrow`

- .changes/unreleased/Dependencies-20240403-134956.yaml
- setup.py
We need to preserve backwards compatibility for installing this package.
Include `dbt-core` as a dependency for installation, but do not depend on it within functional code.
> Add `dbt-core~=1.8.0a1` as convenience dep

- dbt/adapters/bigquery/connections.py
- Preserve nicely formatted timeout exception (#1187)
resolves #
[ADAP-851]: https://dbtlabs.atlassian.net/browse/ADAP-851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> backport 1187 to 1.6.latest

- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
> [Backport 1.2.latest] Pin `macos` runners to `macos-12` (#1195)

- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
> [Backport 1.3.latest] Pin `macos` runners to `macos-12` (#1195)

- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
> [Backport 1.4.latest] Pin `macos` runners to `macos-12` (#1195)

- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
> [Backport 1.5.latest] Pin `macos` runners to `macos-12` (#1195)

- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
> [Backport 1.6.latest] Pin `macos` runners to `macos-12` (#1195)

- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
> [Backport 1.7.latest] Pin `macos` runners to `macos-12` (#1195)

- tests/functional/adapter/test_grant_access_to.py
- tests/unit/test_bigquery_adapter.py
- tests/unit/test_bigquery_connection_manager.py
- remove broken import
resolves #
> remove dependency on dbt-core legacy logger

- .bumpversion.cfg
- setup.py
- tests/functional/adapter/test_grant_access_to.py
remove duplicate package_version and avoid bumping dbt-core version
resolves #
> fix Core version bump in setup.py during release

- dbt/adapters/bigquery/connections.py
This failure is clouding our alerts despite us not supporting this version anymore. Also this problem does not surface on a local run of PyPI. 
Rather than fight whatever is going on, I'm suppressing for expediency. If this were a supported version, it would behoove us to dig in more.
> Suppress warning about 'bad type'.

- .changes/unreleased/Fixes-20240201-145323.yaml
- dbt/include/bigquery/macros/catalog/catalog.sql
resolves #1252
Forward-port the fix from #1085 to `main`. After merging, we will backport to 1.8.latest (for inclusion in next dbt-bigquery v1.8.x path).
> Forward-port fix from #1085

- dev-requirements.txt
- tests/unit/test_bigquery_adapter.py
- tests/unit/test_bigquery_connection_manager.py
resolves #
The way we build testing envornmients means we are pulling in some things that 1.8.latest branch doesn't test against and causing failures.
fix pinning for affected adapters
> constraints update causing test failures in ci/cd

- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
- .pre-commit-config.yaml
- setup.py
- tox.ini
resolves #1104 
Adding Python `3.12` should pass a series of tests
✅ `pytest tests/unit` local
✅ `pytest tests/functional` local
✅  `dbt seed && dbt run` in a local jaffle shop using plain `pip install dbt-redshift` with 3.12 active
✅ smoke testing run using test-bundle on snowflake against the `jaffle-shop-base` scenario with `3.12.X` active
✅ GHA workflow involving integration tests
✅ release workflow still works
No code changes required per my testing above.
> Add support for 3.12 in workflow files and configs

- dev-requirements.txt
When updating the integration.yml workflow, updating dbt-core branch didn't work because the format in dev-requirements.txt didn't match what was expected in update_dev_dependency_branches.sh
Add the "#egg" snippet that the other repos have and that update_dev_dependency_branches.sh expects.
> Make dev-requirements.txt look like other repos and work with update_dev_dependency_branches.sh

- .github/workflows/integration.yml
The new version of `upload-artifacts` requires a unique artifact name for upload whereas the old one allowed for overwriting the existing artifact. This was addressed for the test results, but not the logs resulting from running the tests.
Add the same uniqueness namespace to the logs artifact that is used for the test results artifact.
> Fix the logs upload step for integration tests

- .github/workflows/integration.yml
- tests/functional/adapter/test_grant_access_to.py
- add github.actor to concurrency controls
resolves #
> add github.actor to concurrency controls in integration.yml

- .changes/unreleased/Features-20240925-232238.yaml
- dbt/include/bigquery/macros/materializations/incremental.sql
- dbt/include/bigquery/macros/materializations/incremental_strategy/microbatch.sql
- dev-requirements.txt
- tests/functional/adapter/incremental/incremental_strategy_fixtures.py
- tests/functional/adapter/incremental/test_incremental_microbatch.py
resolves #1354
As part of https://github.com/dbt-labs/dbt-core/issues/10624, dbt-bigquery needs to implement a microbatch incremental strategy.
* Ensuring partition_by is set + has the same granularity as batch_size
* Calling insert_overwrite, which will use dynamic partition if partitions not set
* Follow up: static microbatch for perf improvement: https://discourse.getdbt.com/t/benchmarking-incremental-strategies-on-bigquery/981 🚀
> Microbatch Strategy

- .changes/unreleased/Fixes-20241001-193207.yaml
- dbt/adapters/bigquery/connections.py
We were not catching a database exception and then returning the result as a runtime exception. This was caught in a test that was recently updated to expect a database exception. The functionality that changed used to not run this code at all, hence it used to pass.
Add another condition for catching database exceptions.
> Catch google `NotFound` exception as a `DbtDatabaseError`

- .changes/unreleased/Breaking Changes-20241016-185117.yaml
- .github/scripts/integration-test-matrix.js
- .github/workflows/integration.yml
- .github/workflows/main.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- dev-requirements.txt
- docker/Dockerfile
- docker/dev.Dockerfile
- setup.py
- tox.ini
Python 3.8 reached end of life on 10/7/2024.
Drop support for Python 3.8. Update tests to no longer run on Python 3.8.
> Drop support for Python 3.8

- .github/workflows/main.yml
We removed an extra line when resolving merge conflicts with `main` on a recent PR. This puts that line back.
> Add matrix entry back that was inadvertently removed during a sync with main

- .changes/unreleased/Fixes-20240226-233024.yaml
- dbt/adapters/bigquery/impl.py
- dbt/include/bigquery/macros/materializations/seed.sql
- tests/functional/adapter/test_simple_seed.py
- implement choice of delimiter for seed files (#1122)
resolves #
> backport 1122 to 1.8.latest

- .changes/unreleased/Fixes-20241028-172719.yaml
- dbt/include/bigquery/macros/materializations/table.sql
- tests/functional/adapter/test_grant_access_to.py
resolves #1318
In order to support partitioned materializations in BQ python models we we switched from "direct" to "indirect" mode when writing model results in Dataproc back to BigQuery. As the naming implies "indirect" temporarily stages data in the provided GCS bucket. If a user has a retention policy on the bucket this will fail as the bucket won't allow Dataproc to delete these temp files as it goes. 
This PR sidesteps that issue to ensure backwards compatibility with <1.7 created models by using "direct" write when a partitioned config is not provided.  
Note: I have not added any new testing to cover the case where a user has set a retention policy. Ultimately I think this is an edge case we don't need to test against but we should document that a bucket retention policy cannot be …
> use "direct" write for non-partitioned python model materializations

- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
`macos-12` will not be supported as a GHA runner soon.
Update to `macos-14`, which corresponds to `macos-latest`.
> Update macos runners from macos-12 to macos-14

- .changes/unreleased/Fixes-20241205-133606.yaml
- dbt/adapters/bigquery/connections.py
resolves #
We added a custom retry predicate in a call to `get_table` when adding the retry factory and it appears to be missing some retryable errors (versus the default).
Remove the custom retry and use the built in default.
> Remove custom retry in get_table call

- .changes/unreleased/Fixes-20241204-105846.yaml
- dbt/adapters/bigquery/relation.py
- tests/functional/adapter/incremental/incremental_strategy_fixtures.py
- tests/functional/adapter/incremental/test_incremental_microbatch.py
resolves https://github.com/dbt-labs/dbt-bigquery/issues/1412
It's not currently possible to use microbatch models with inputs that aren't of type `timestamp`, because BigQuery does not coerce dates or datetimes to timestamps automatically when compared to literal timestamps. 
Cast `event_time` to timestamp on rendering, prior to comparing against timestamp literal.
https://cloud.google.com/bigquery/docs/reference/standard-sql/conversion_functions#cast_as_timestamp
works for inputs of type: 
* string
* date - assumes midnight UTC
* datetime - assumes UTC
* timestamp 
(shoutout to @jtcohen6 for helping with this solutioning)
> Fix: Cast to timestamp prior to event time comparison

- .changes/unreleased/Features-20241202-223835.yaml
- dbt/include/bigquery/macros/materializations/incremental.sql
- tests/functional/adapter/incremental/incremental_strategy_fixtures.py
- tests/functional/adapter/incremental/test_incremental_microbatch.py
resolves #
https://github.com/dbt-labs/dbt-bigquery/issues/1414
`copy_partitions` was only being allowed for insert_overwrite, but it makes sense to allowlist it when using `microbatch` too.
Allowlist `copy_partitions` as part of `microbatch` too.
> [Feature] Allow `copy_partitions` when using `microbatch`

- tox.ini
One of the python model tests takes just over 10 minutes to complete when run locally. However, we specify a timeout of 10 minutes in `tox.ini`.
Bump the timeout from 10 minutes to 15 minutes to allow the test to complete. This doesn't appear to be an issue in newer versions of `dbt-bigquery`, so it's not necessary to apply this change to newer versions.
> Update the pytest timeout from 10min to 15min for python tests

- .github/workflows/integration.yml
We're defaulting to `main` in integration tests for the adapter and core branches. The scheduled release branch tests don't pass inputs, so they check out 1.9.latest and then that workflow in turn checks out the default, `main`. This does not affect prior release branches since the functionality to select a branch was introduced after we cut the `1.8.latest` branch.
- update the defaults for `dbt-core` and `dbt-bigquery` to be `1.9.latest`
- handle future release branch tests in the monorepo
> Update the default inputs on the integration tests workflow to match the branch

- .changes/unreleased/Fixes-20241211-144752.yaml
- dbt/adapters/bigquery/retry.py
- tests/unit/test_bigquery_connection_manager.py
resolves #263
We're not retrying in all scenarios that BigQuery recommends. This is causing unexpected behavior for users. This likely happened as a result of us maintaining our own list of retryable errors, which fell out of sync with BigQuery's development over time.
Instead of maintaining our own list, we should rely on BigQuery's list of retryable errors and reasons. However, we have one scenario that is not covered by BigQuery's defaults, `BadRequest`. We need to also check this scenario after checking BigQuery's defaults to maintain backwards compatibility.
> [Bug] Use bigquery default retryable exceptions

- .github/workflows/main.yml
The build verification check is broken. We only build one artifact, py39 on ubuntu, but then we download it several times and check it under the premise that we're checking various Python versions and OS's. Additionally, we broke prior build verification checks by removing the upload and download steps that happen between these jobs.
We should instead run the two jobs as one single job and apply the matrix to the whole job. This will correctly test each build scenario and avoid the need for uploading and downloading artifacts.
> Combine build verification jobs to avoid needing to upload and download artifacts

- .github/workflows/main.yml
Backport #1461 to `1.5.latest`
> [Backport 1.5.latest] Combine build verification jobs to avoid needing to upload and download artifacts (#1461)
