dbt/adapters/bigquery/connections.py, dbt/adapters/bigquery/gcloud.py, dbt/adapters/bigquery/impl.py
resolves #8
Fixed issue with missing gcloud import, moved gcloud.py into dbt-bigquery codebase and updated import statements.
=> Moved gcloud file into dbt-bigquery codebase

CHANGELOG.md, dbt/adapters/bigquery/connections.py
resolves #4267
Adding the optional `execution_project` param from `profile.yml` to the `target` object.
=> Adding execution_project to target object

.bumpversion.cfg, CHANGELOG.md, dbt/adapters/bigquery/__version__.py
=> [Backport] Bumping version to 1.0.0 (#80)

setup.py
=> Fixing version naming issue

.bumpversion.cfg, setup.py
resolves #83 
Updating the version bump file to include `setup.py`
=> Updating version bumping script

.github/workflows/integration.yml, .github/workflows/main.yml, .github/workflows/version-bump.yml
Following the lead of this PR in Core: https://github.com/dbt-labs/dbt-core/pull/5320 to fix CI failures caused by pip
=> Fixing pip upgrade for CI

.github/workflows/integration.yml
first part of PR to resolve #233
We use the github action definition on `main` branch to run all tests, so we will have to add the env var there first and then enable the tests
=> add env var for python model test

dev-requirements.txt, setup.py, tests/functional/adapter/test_python_model.py, tox.ini
=> Add extra requirements in setup.py and skip python model tests

CHANGELOG.md, dbt/adapters/bigquery/connections.py, tests/integration/bigquery_test/test_bigquery_adapter_functions.py
Reverts dbt-labs/dbt-bigquery#225
=> Revert "Add job_id/project_id to adapter response to enable easy job linking"

.github/workflows/changelog-existence.yml
resolves NA
The file extension in the URL must be lower cases.
=> Fix a typo in `changelog-existence.md`

.changes/unreleased/Under the Hood-20220825-073235.yaml, dbt/include/bigquery/macros/materializations/incremental.sql, dbt/include/bigquery/macros/materializations/table.sql
=> add supported language

.pre-commit-config.yaml, dbt/adapters/bigquery/python_submissions.py, dbt/include/bigquery/macros/materializations/table.sql
resolves #
This will resolve the long gap between job done to operation gets result back
=> fix operation wait for cluster submission

dbt/adapters/bigquery/impl.py, tests/integration/sources_test/test_sources.py
resolves #
Update function following CORE#5949. Not sure this is actually a good idea, it is marked as a private function.
=> update following changes in CORE#5949

.github/workflows/integration.yml, .github/workflows/main.yml
resolves #https://github.com/dbt-labs/dbt-core/issues/6203
Upgrade actions/setup-python from v2 to v4.3.0 to bring in all the updates for deprecations
Defines Python Version to use when installing dependencies
=> [CT-1469] init pr for short term python version issue fix

.github/workflows/integration.yml, .github/workflows/main.yml
resolves #https://github.com/dbt-labs/dbt-core/issues/6203
Upgrade actions/setup-python from v2 to v4.3.0 to bring in all the updates for deprecations
Defines Python Version to use when installing dependencies
=> [Backport][CT-1469] init pr for short term python version issue fix (#375)

.changes/unreleased/Under the Hood-20221202-161030.yaml, .github/workflows/main.yml
resolves #405 
new python error in workflow in github actions
=> [CT-1594] updating workflow

.changes/unreleased/Under the Hood-20221207-151813.yaml, tox.ini
* fixing env write out in tox due to 4.0.0 release
* finish tox alignment and add changelog
* minor fix for format
* add changelog
* remove uneeded changie entry
resolves #411.
=> [Backport 1.0.latest] updating passenv in tox 

.changes/unreleased/Features-20230109-105921.yaml, .github/workflows/main.yml, dbt/include/bigquery/macros/catalog.sql
resolves #173, #174 
updates query catalog to include table description if it exists
=> take over of PR #174 to get changelog in order to merge

.github/workflows/release.yml
=> fix release.yml pypi steps

.github/workflows/release-branch-tests.yml
resolves https://github.com/dbt-labs/dbt-core/issues/6597
Adds both `1.3.latest` and `1.4.latest` to testing matrix
=> add 1.3 and 1.4 to testing matrix

.bumpversion.cfg, .github/workflows/nightly-release.yml, .github/workflows/release.yml, setup.py
resolves #543 
Runs against 1.4.latest and fixes version bugs.
=> Fix nightly release test

.bumpversion.cfg, .github/workflows/nightly-release.yml, setup.py
port https://github.com/dbt-labs/dbt-bigquery/pull/545 to main
Fixes nightly release tests
=> Fix nightly release test (#545)

.changes/unreleased/Under the Hood-20230223-105149.yaml, dbt/include/bigquery/macros/adapters.sql
resolves #548
Rename "constraints_enabled" to "contract"
=> Rename constraints_enabled to contract

.changes/unreleased/Fixes-20221213-102005.yaml, dbt/adapters/bigquery/dataset.py, dbt/adapters/bigquery/impl.py, tests/functional/adapter/test_grant_access_to.py, tests/unit/test_bigquery_adapter.py, tests/unit/test_dataset.py
resolves #https://github.com/dbt-labs/dbt-bigquery/issues/522
fix duplicate authorized views in 1.4
As noted in #522 following the steps to reproduce would indeed throw the `duplicate authorized views` error 
however if we backport #404 the run looks like
```
(env) ➜  jaffle-shop git:(master) ✗ (env) ➜  jaffle-shop git:(master) ✗ dbt run
18:39:09  Running with dbt=1.4.2-rc1
18:39:09  Found 2 models, 1 test, 0 snapshots, 0 analyses, 571 macros, 0 operations, 2 seed files, 0 sources, 0 exposures, 0 metrics
18:39:09
18:39:11  Concurrency: 1 threads (target='dev')
18:39:11
18:39:11  1 of 2 START sql view model dbt_mcknight.my_model .............................. [RUN]
18:39:12  1 of 2 OK created sql view model dbt_mcknight.my_model ......................... [CREATE VIEW (0 processed) in …
```
=> [Backport] 404

.changes/unreleased/Fixes-20230202-010332.yaml, dbt/adapters/bigquery/impl.py, dbt/include/bigquery/macros/materializations/incremental_strategy/common.sql, dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql, tests/functional/adapter/incremental/incremental_strategy_fixtures.py, tests/functional/adapter/incremental/seeds.py, tests/functional/adapter/incremental/test_incremental_strategies.py, tests/functional/adapter/simple_bigquery_view/fixtures.py, tests/functional/adapter/simple_bigquery_view/seeds.py, tests/functional/adapter/simple_bigquery_view/test_simple_bigquery_view.py
=> backport 485 to 1.4.latest

.changes/unreleased/Features-20230223-145508.yaml, dbt/include/bigquery/macros/adapters.sql, dev-requirements.txt, tests/functional/adapter/test_constraints.py
resolves #555 
Support contracts for view materializations.
=> support contracts on models materialized as view

.changes/unreleased/Under the Hood-20230306-150009.yaml, .github/scripts/update_dependencies.sh, .github/scripts/update_release_branch.sh, .github/workflows/cut-release-branch.yml
…ase action
resolves #583, #https://github.com/dbt-labs/actions/issues/76
adds two new scripts to be triggered by actions workflow
=> add new scripts for cut-release workflow

.github/scripts/integration-test-matrix.js, .github/workflows/integration.yml, .github/workflows/main.yml, dev_requirements.txt, tox.ini
resolves #
Similar to (https://github.com/dbt-labs/dbt-core/pull/7095)
=> Remove 3.9 from main workflow

.changes/unreleased/Features-20230303-132509.yaml, dbt/adapters/bigquery/connections.py, dbt/adapters/bigquery/python_submissions.py, dbt/include/bigquery/macros/python_model/python.sql, dev-requirements.txt, tests/unit/test_bigquery_adapter.py, tests/unit/test_configure_dataproc_batch.py, tox.ini
=> backport pr #578

.changes/unreleased/Fixes-20230315-130504.yaml, tests/integration/persist_docs_tests/models-bigquery-nested/schema.yml, tests/integration/persist_docs_tests/test_persist_docs.py
backports #607 
Same procedure as the last one
=> Backport PR 607 manually to 1.2.latest.

.changes/unreleased/Fixes-20230315-130504.yaml, tests/integration/persist_docs_tests/models-bigquery-nested/schema.yml, tests/integration/persist_docs_tests/test_persist_docs.py
=> Backport/605 to 1.3.latest

.changes/unreleased/Fixes-20230315-130504.yaml, tests/integration/persist_docs_tests/models-bigquery-nested/schema.yml, tests/integration/persist_docs_tests/test_persist_docs.py
=> Backport/605 manually to 1.4.latest

.changes/1.5.0/Under the Hood-20230223-105149.yaml, .changes/unreleased/Under the Hood-20230223-105149.yaml, dbt/include/bigquery/macros/adapters.sql, dev-requirements.txt
resolves #633
contract config is now an object in `dbt-core` https://github.com/dbt-labs/dbt-core/pull/7222
=> update to retrieve contract enforced from dict

.changes/unreleased/Fixes-20230411-143515.yaml, dev-requirements.txt
=> Repair accidental change to dev-requirements

.changes/1.5.0/Features-20221220-193731.yaml, dbt/adapters/bigquery/impl.py, dev-requirements.txt, tests/functional/adapter/test_constraints.py
resolves #568
Uses centralized warnings from `dbt-core` for constraints.  Adds custom text for primary key per docs.
=> update for generalized constraint warnings

.github/workflows/integration.yml, .github/workflows/main.yml, .github/workflows/release-branch-tests.yml
resolves #678 
Update versions of used Github Actions ahead of:
[node12 deprecation](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) (Summer 2023)
[set-output deprecation](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) (fully disabled on 31st May 2023)
=> update used gh actions ahead of set-output, node12 deprecation

.changes/unreleased/Fixes-20230508-163251.yaml, dbt/adapters/bigquery/impl.py, tests/functional/test_delete_column_policy.py
resolves https://github.com/dbt-labs/dbt-bigquery/issues/687
backport of the PR: #688
=> Backport #688 to 1.5.latest

.github/workflows/integration.yml, .github/workflows/main.yml
resolves #678 
Fixes a few overlooked instances of set-output
=> updating set-output

.github/workflows/integration.yml, .github/workflows/main.yml
resolves #678 
Backport to `1.4.latest`.  Does not require a patch release since this is only around testing automation.
=> [Backport] 1.4.latest gh deprecations

.github/workflows/integration.yml, .github/workflows/main.yml
resolves #678 
Backport to `1.5.latest`.  Does not require a patch release since this is only around testing automation.
=> [Backport] 1.5.latest gh deprecations

.github/workflows/release-branch-tests.yml
resolves #515 
This was merged before I was able to update the branch the workflow pointed to.
=> Fix workflow branch

.github/workflows/integration.yml, .github/workflows/main.yml
resolves #
Looks like some work we did around a year ago around unnecessary installs of core in actions needs to be taken care of here as support drop for 3.7 causes issues. 
will need to be backported as far back as 1.0 or 1.1 and make sure dev_requirements points to correct .latest branch of core for install
=> remove unneeded install of core

.github/workflows/integration.yml, .github/workflows/main.yml
=> [BACKPORT] remove unneeded install of core (#744)

.github/workflows/integration.yml, scripts/env-setup.sh, test.env.example
resolves #
updates a env for testing
=> [BACKPORT] #758 to 1.5.latest

.github/workflows/integration.yml, .github/workflows/nightly-release.yml, scripts/env-setup.sh, test.env.example
resolves #
updates env for testing
=> [BACKPORT] #758 to 1.3.latest 

.github/workflows/integration.yml, .github/workflows/nightly-release.yml, scripts/env-setup.sh, test.env.example
resolves #
updates env for testing
=> [BACKPORT] #758 to 1.2.latest

.github/workflows/nightly-release.yml, scripts/env-setup.sh, test.env.example
resolves #
updates env for testing and update nightly release file
=> [BACKPORT] #758 to 1.1.latest and change nightly release pointer

.github/workflows/integration.yml, scripts/env-setup.sh, test.env.example
resolves #
updates env for testing
=> [BACKPORT] #758 to 1.4.latest

.changes/unreleased/Fixes-20230511-143217.yaml, dev-requirements.txt, tests/functional/adapter/test_constraints.py
=> [Backport] 698 to 1.5.latest

tests/functional/adapter/test_constraints.py
(cherry picked from commit 580ad7649ffb00f7220938cca4cc4bc533b8d124)
resolves #
=> Test constraint rendering with column quoting (#713)

.changes/unreleased/Features-20230601-141255.yaml, dbt/adapters/bigquery/column.py, dbt/adapters/bigquery/impl.py, dbt/include/bigquery/macros/utils/get_columns_spec_ddl.sql, tests/functional/adapter/constraints/fixtures.py, tests/functional/adapter/constraints/test_constraints.py, tests/unit/test_column.py
(cherry picked from commit b1e950bf6f8f6c3528b65080e257b746839ef87c)
=> [Backport] model contracts + constraints with nested fields (#738)

tests/unit/utils.py
=> add dependent_projects_dict to utils.py 

.changes/unreleased/Breaking Changes-20230530-174051.yaml, .github/scripts/integration-test-matrix.js, .github/workflows/main.yml, CONTRIBUTING.md, dev-requirements.txt, setup.py, tox.ini
- Drop support for py37 (#742)
resolves #
=> backport 742 to 1.5.latest

.changes/unreleased/Breaking Changes-20230530-174051.yaml, .github/scripts/integration-test-matrix.js, .github/workflows/main.yml, CONTRIBUTING.md, setup.py, tox.ini
Backport bc8b4a4a3eff0b4a0f0e1a760c35f6e26e4bde21 from #795.
=> [Backport 1.0.latest] Dropping support for py37 (#742)

tests/functional/adapter/hooks/data/seed_model.sql, tests/functional/adapter/hooks/data/seed_run.sql
resolves #https://github.com/dbt-labs/dbt-core/issues/7941, pr: https://github.com/dbt-labs/dbt-core/pull/7942
adds `thread_id` to seed file to match new field in core tests for snowflake
=> add thread_id to seeds for hooks tests to fix failure caused by change in core

.github/pull_request_template.md
resolves #  
recent merge seems to of introduced a white space issue causing `code quiality` tests to fail in ci/cd
=> fix whitespace change

tests/functional/adapter/store_test_failures_tests/test_store_test_failures.py
resolves #803
resolves # hanging artifacts left during test runs due to change in schema name not caught by default teardown method
=> [BACKPORT] backport teardown_method for test

.github/scripts/update_dbt_core_branch.sh, .github/workflows/integration.yml
=> add input to allow testing against a non-main core branch

.github/workflows/integration.yml, dev-requirements.txt, tox.ini
backport https://github.com/dbt-labs/dbt-bigquery/pull/829
=> [Backport 1.6.latest] Add Datadog Env Vars

.github/workflows/integration.yml, dev-requirements.txt, tox.ini
backport https://github.com/dbt-labs/dbt-bigquery/pull/829
=> [Backport 1.5.latest] Add Datadog Env Vars

.github/workflows/integration.yml, dev-requirements.txt, tox.ini
backport https://github.com/dbt-labs/dbt-bigquery/pull/829
=> [Backport 1.4.latest] Add Datadog Env Vars

.changes/unreleased/Fixes-20230818-214616.yaml, dbt/adapters/bigquery/__init__.py, dbt/adapters/bigquery/impl.py, tests/unit/test_bigquery_adapter.py
* case insensitive check on partition matching
* Review change
---------
resolves #886 
=> [BACKPORT] ADAP-834 case insensitive check on partition matching (#888)

.changes/unreleased/Fixes-20230821-180758.yaml, tests/functional/adapter/expected_stats.py
resolves # reverts fix added in #890 to go along with core change https://github.com/dbt-labs/dbt-core/pull/8306. revert should be paired with merge of https://github.com/dbt-labs/dbt-core/pull/8478 and backported to 1.6.latest on merge
=> revert change made in pr 890 to go along with core revert

.changes/unreleased/Under the Hood-20230922-114217.yaml, dbt/adapters/bigquery/connections.py, tests/functional/adapter/test_grant_access_to.py
- update SQLQuery to include node_info
resolves #
=> Update SQLQuery to include node_info

.changes/unreleased/Fixes-20230804-005817.yaml, dbt/include/bigquery/macros/adapters/columns.sql
* add current_timestamp to prevent empty query caching
* add changie log
(cherry picked from commit 1b8cae258618106eb4e2af747d464696c14bb8ba)
resolves #
=> [Backport] Fix contact validation failure on query data types change (#862)

.changes/unreleased/Under the Hood-20230925-143628.yaml, tests/functional/adapter/dbt_show/test_dbt_show.py
=> [Backport] 927 and fix core pointer

.changes/unreleased/Under the Hood-20230925-143628.yaml, tests/functional/adapter/dbt_show/test_dbt_show.py
=> [Backport] pr 927 and fix core pointer

.github/workflows/docs-issue.yml
resolves #https://github.com/dbt-labs/actions/issues/111
Overlooking docs changes related to `dbt-core` and adapters changes
Automate the creation of docs issues by adding the `user docs` a label to merged PRs
=> add docs-issue workflow to dbt-bigquery

.changes/unreleased/Fixes-20231025-223003.yaml, dbt/adapters/bigquery/relation_configs/_options.py, dbt/include/bigquery/macros/relations/materialized_view/drop.sql, dbt/include/bigquery/macros/relations/materialized_view/refresh.sql
=> Fix refresh syntax, config comparison with empty labels

.changes/unreleased/Fixes-20231219-153446.yaml, dbt/adapters/bigquery/connections.py, tests/functional/adapter/dbt_show/test_dbt_show.py, tests/functional/adapter/test_grant_access_to.py
=> 1.7.latest remove _json_from_json patch

.changes/unreleased/Fixes-20230804-005817.yaml, dbt/include/bigquery/macros/adapters/columns.sql
Backport 1b8cae258618106eb4e2af747d464696c14bb8ba from #862
=> [Backport 1.5.latest] Fix contract validation failure on query data types change

dev-requirements.txt, tests/functional/adapter/test_grant_access_to.py
- use dbt-common main to test against
resolves #
=> Use dbt-common main in dev-requirements.txt

.changes/unreleased/Fixes-20240216-133319.yaml, dbt/adapters/bigquery/connections.py
=> Remove refresh token field from connection keys

setup.py, tests/functional/adapter/test_grant_access_to.py
- update install_requires to allow for pre-release common/adapters
resolves #
=> allow for pre-release common/adapters

.changes/unreleased/Dependencies-20240319-102258.yaml, dev-requirements.txt
=> [Backport 1.2.latest] Test ddtrace dependency range (#1141)

.changes/unreleased/Dependencies-20240319-102258.yaml, dev-requirements.txt
=> [Backport 1.3.latest] Test ddtrace dependency range (#1141)

.changes/unreleased/Under the Hood-20240410-182121.yaml, .github/dependabot.yml
We have inconsistent and under-configured dependabot config files.
Consistify them.
=> Update dependabot config to cover GHA

.pre-commit-config.yaml, tests/unit/test_bigquery_adapter.py
See https://github.com/dbt-labs/dbt-adapters/issues/144
=> Add pre-commit check for dbt-core

dbt/adapters/bigquery/connections.py
* use dynamic schema in test_grant_access_to.py
* use dynamic schema in test_grant_access_to.py
* revert setup
* Add descriptive error message on query timeout
* Add descriptive error message on query timeout
(cherry picked from commit b62ce7469a47de4e1f526fc551817b3e0919ddb2)
resolves #
=> Preserve nicely formatted timeout exception (#1187)

.changes/unreleased/Fixes-20240423-131752.yaml, dbt/adapters/bigquery/relation.py, tests/functional/adapter/empty/test_empty.py, tests/functional/adapter/test_grant_access_to.py
see: https://github.com/dbt-labs/dbt-adapters/issues/124
=> Stop adding aliases to render_limited output

.github/scripts/integration-test-matrix.js, .github/workflows/main.yml
=> [Backport 1.0.latest] Pin `macos` runners to `macos-12` (#1195)

tests/functional/python_model_tests/test_list_inference.py
…hon test run
resolves test failures from merge of #1205 
A new python test was misnamed causing it to run during normal functional test workflow instead of the python model workflow where it should.
issue found from nightly test runs: https://github.com/dbt-labs/dbt-bigquery/actions/runs/9002717952
update the name of test from `TestListInference` to `TestPythonListInference` and test it goes through correct workflow in ci/cd and test locally.
will also need to backport to tie in with pr `1205` backports
=> update TestListInference to TestPythonListInference 

.bumpversion.cfg, setup.py
- fix Core version bump in setup.py during release (#1241)
resolves #
=> backport 1241 to 1.8.latest

.github/workflows/release-internal.yml, tests/functional/adapter/test_grant_access_to.py
-
- Update internal release naming and arguments
resolves #
=> Update internal release naming and arguments

dev-requirements.txt, tests/functional/adapter/dbt_show/test_dbt_show.py
Followon from [Base Adapter #207](https://github.com/dbt-labs/dbt-adapters/pull/249)
We should be testing for this!
Add the test.
=> Base 207/add test

.github/workflows/main.yml
=> [Backport 1.2.latest] Swap the order of the sdist and wheel checks (#1285)

.github/workflows/main.yml
=> [Backport 1.1.latest] Swap the order of the sdist and wheel checks (#1285)

.github/workflows/main.yml
=> [Backport 1.0.latest] Swap the order of the sdist and wheel checks (#1285)

.github/workflows/integration.yml
=> [Backport/1.8.latest] Fix CI concurrency issue

.github/workflows/integration.yml, setup.py, tests/functional/adapter/test_grant_access_to.py
- update dbt-common dependency to 1.10 and dbt-adapters to 1.7
resolves #
=> update dbt-common dependency to 1.10 and dbt-adapters to 1.7

.changes/unreleased/Breaking Changes-20241016-185117.yaml, .github/scripts/integration-test-matrix.js, .github/workflows/integration.yml, .github/workflows/main.yml, .pre-commit-config.yaml, CONTRIBUTING.md, Makefile, setup.py, tox.ini
=> [Backport 1.8.latest] Drop support for Python 3.8

.changes/unreleased/Breaking Changes-20241016-185117.yaml, .github/scripts/integration-test-matrix.js, .github/workflows/integration.yml, .github/workflows/main.yml, .pre-commit-config.yaml, CONTRIBUTING.md, Makefile, setup.py, tox.ini
=> [Backport 1.7.latest] Drop support for Python 3.8

.changes/unreleased/Breaking Changes-20241016-185117.yaml, .github/scripts/integration-test-matrix.js, .github/workflows/main.yml, .pre-commit-config.yaml, CONTRIBUTING.md, Makefile, setup.py, tox.ini
=> [Backport 1.6.latest] Drop support for Python 3.8

.changes/unreleased/Breaking Changes-20241016-185117.yaml, .github/scripts/integration-test-matrix.js, .github/workflows/main.yml, .pre-commit-config.yaml, CONTRIBUTING.md, Makefile, setup.py, tox.ini
=> [Backport 1.4.latest] Drop support for Python 3.8

.changes/unreleased/Breaking Changes-20241016-185117.yaml, .github/scripts/integration-test-matrix.js, .github/workflows/main.yml, .pre-commit-config.yaml, CONTRIBUTING.md, Makefile, setup.py, tox.ini
=> [Backport 1.5.latest] Drop support for Python 3.8

.github/scripts/integration-test-matrix.js, .github/workflows/main.yml
=> update macos runners from macos-12 to macos-14 (#1394)

docker/Dockerfile, tests/functional/adapter/test_grant_access_to.py
- update libpq-dev dependency to 13.18-0+deb11u1
resolves #
=> update libpq-dev dependency to 13.18-0+deb11u1

.changes/unreleased/Fixes-20241205-133606.yaml, dbt/adapters/bigquery/connections.py
duplicate of #1424 which got jammed
=> Backport 1423 to 1.9.latest

.github/workflows/integration.yml, .github/workflows/main.yml
=> Update upload artifacts 1.4

.github/workflows/integration.yml, .github/workflows/main.yml
=> Update upload artifacts 1.5

.github/workflows/integration.yml, .github/workflows/main.yml
=> Update upload artifacts 1.6

.github/workflows/integration.yml, .github/workflows/main.yml
=> Update upload artifacts 1.7

.github/workflows/integration.yml, .github/workflows/main.yml
=> Update upload artifacts 1.8

.github/workflows/main.yml
=> Remove the artifacts related workflow steps

.github/workflows/main.yml
=> Remove artifacts steps 1.5

dev-requirements.txt
Backport #1459 to `1.8.latest`
=> [Backport 1.8.latest] Update dbt-adapters ref to point to the subdirectory

.github/workflows/main.yml
Backport #1461 to `1.4.latest`
=> [Backport 1.4.latest]

.github/workflows/main.yml
Backport #1461 to `1.6.latest`
=> [Backport 1.6.latest] Combine build verification jobs to avoid needing to upload and download artifacts (#1461)

.github/workflows/main.yml
Backport #1461 to `1.7.latest`
=> [Backport 1.7.latest] Combine build verification jobs to avoid needing to upload and download artifacts (#1461)

.github/workflows/main.yml
Backport #1461 to `1.8.latest`
=> [Backport 1.8.latest] Combine build verification jobs to avoid needing to upload and download artifacts (#1461)
